language: node_js
node_js:
  - "12"
script:
  - touch env.txt
  - echo BASE_NAME=$name > env.txt
  - cat env.txt
  - echo "skipping tests"
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key: "99ba167725c816ad280852bfcfaf7dcdd136baee"
  file: "testing-pk"
  skip_cleanup: true
  draft: true
