language: node_js
node_js:
  - "12"
script:
  - touch env.txt
  - echo BASE_NAME=$name > env.txt
  - cat env.txt
  - echo "skipping tests"
before_deploy:
  - echo "Before deploy"
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "38d082192f3cf333187ed9dcbf7f3fc4aaaabd57"
  file: "testing-pk"
  skip_cleanup: true
  on:
    tags: true
